"use client";
import Link from "next/link";

export function Preamble() {
  return (
    <div className="privacy-policy">
      {/* Introduction */}
      <section className="max-w-6xl p-6 md:p-12 mx-auto text-lg text-gray-700 space-y-6">
        <h2 className="text-2xl">Introduction</h2>
        <p>
          This Privacy Policy describes Our policies and procedures on the
          collection, use, and disclosure of Your information when You use the
          Service, and informs You about Your privacy rights and how the law
          protects You. We use Your Personal Data to provide and improve the
          Service. By using the Service, You agree to the collection and use of
          information in accordance with this Privacy Policy.
        </p>
        <p>
          This Privacy Policy is in compliance with applicable data protection
          laws, including the{" "}
          <span className="font-semibold">
            Kenya Data Protection Act, 2019,
          </span>{" "}
          which governs the processing of personal data within Kenya. We are
          committed to ensuring that Your Personal Data is handled lawfully,
          fairly, and transparently in accordance with the provisions of this
          Act.
        </p>
        {/* Interpretation */}
        <h2 className="text-2xl">Interpretation</h2>
        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        {/* Definitions */}
        <h2 className="text-2xl">Definitions</h2>
        <p>For the purposes of this Privacy Policy:</p>
        <ul role="list" className="list-disc marker:text-sky-400">
          <li>
            <strong>Data Controller</strong>
            <p>
              A data controller is an entity that determines the purpose and
              means of processing of personal data. An entity refers to a
              natural or legal person, public authority, agency or other body
              which, alone or jointly with others.{" "}
              <Link href="https://www.odpc.go.ke/" className="text-blue-600">
                Office of the Data Protection Commissioner (ODPC)
              </Link>
            </p>
          </li>
          <li>
            <strong>Data Subject</strong>
            <p>
              Refers to any individual person who can be identified, directly or
              indirectly, via an identifier/personal data.{" "}
              <Link href="https://www.odpc.go.ke/" className="text-blue-600">
                Office of the Data Protection Commissioner (ODPC)
              </Link>
            </p>
          </li>

          <li>
            <strong>Company</strong>{" "}
            <p>
              (referred to as either <strong>"the Company"</strong>,{" "}
              <strong>"We"</strong>, <strong>"Us"</strong>, or{" "}
              <strong>"Our"</strong>in this Agreement)refers to
              <strong> Leti Realty Ltd.</strong>
            </p>
          </li>
          <li>
            <strong>Cookies</strong>{" "}
            <p>
              Cookies are small files that are placed on Your computer, mobile
              device or any other device by a website, containing the details of
              Your browsing history on that website among its many uses.
            </p>
          </li>

          <li>
            <strong>Device</strong>
            <p>
              Means any device that can access the Service such as a computer, a
              cellphone or a digital tablet.
            </p>
          </li>
          <li>
            <strong>Personal Data</strong>
            <p>
              Personal Data is any information that relates to an identified or
              identifiable individual.
            </p>
          </li>
          <li>
            <strong>Service</strong>
            <p>Refers to the Website.</p>
          </li>
          <li>
            <strong>Service Provider</strong>
            <p>
              Means any natural or legal person who processes the data on behalf
              of the Company. It refers to third-party companies or individuals
              employed by the Company to facilitate the Service, to provide the
              Service on behalf of the Company, to perform services related to
              the Service or to assist the Company in analyzing how the Service
              is used.
            </p>
          </li>
          <li>
            <strong>Usage Data</strong>
            <p>
              Refers to data collected automatically, either generated by the
              use of the Service or from the Service infrastructure itself (for
              example, the duration of a page visit).
            </p>
          </li>

          <li>
            <strong>Website</strong>
            <p>
              Refers to Leti Realty Ltd, accessible from{" "}
              <Link href="https://letirealty.com/" className="text-blue-600">
                www.letirealty.com
              </Link>
            </p>
          </li>
          <li>
            <strong>You</strong>
            <p>
              Means the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable.
            </p>
          </li>
        </ul>
      </section>
    </div>
  );
}

export function DataUsage() {
  return (
    <section className="max-w-6xl p-6 md:p-12 mx-auto text-lg text-gray-700 space-y-6">
      <h2 className="text-2xl md:text-3xl font-light text-blue-900  mb-4">
        {" "}
        Collecting and Using Your Personal Data
      </h2>{" "}
      <strong>1. Data Controller</strong>
      <p>
        We (Leti Realty Ltd) are the Data Controller under the Kenya Data
        Protection Act, 2019. This means we are responsible for collecting and
        managing your personal data when you fill in any of our forms (sale
        request, contact, booking). If you have any questions, you can contact
        us at:
      </p>
      <ul role="list" className="list-disc marker:text-sky-400">
        <li>Email: info@letirealty.com</li>
        <li>Phone: +254 798 752 814</li>
      </ul>
      <strong>2. Personal Data That We Collect</strong>
      <p>
        When you fill our property sale request form, contact form, or booking
        form for property viewings, we collect the following personal data:
      </p>
      <ul role="list" className="list-disc marker:text-sky-400">
        <li>Name</li>
        <li>Phone number</li>
        <li>Email address</li>
        <li>Property information (property sale request form)</li>
      </ul>
      <div>
        <strong>3. Usage Data</strong>
        <p>
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </p>
        <p>
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to the IP address of Your device
        </p>
      </div>
      <div>
        <strong>4. Tracking Technologies and Cookies</strong>
        <p>
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Tracking technologies
          used are beacons, tags, and scripts to collect and track information
          and to improve and analyze Our Service. The technologies We use may
          include:
        </p>
      </div>
      <div>
        <strong>5. Cookies or Browser Cookies</strong>
        <p>
          A cookie is a small file placed on Your Device. You can instruct Your
          browser to refuse all Cookies or to indicate when a Cookie is being
          sent. However, if You do not accept Cookies, You may not be able to
          use some parts of our Service. Unless you have adjusted Your browser
          setting so that it will refuse Cookies, our Service may use{" "}
          <Link href="/legal/cookie-policy" className="text-blue-600">
            Cookies.
          </Link>
        </p>
      </div>
      <div>
        <p>
          <strong>6. Purpose & Legal Basis for Collection</strong>
        </p>
        <p>We collect and use your personal data for the following purposes:</p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-6 ">
          <div>
            <strong>Purpose</strong>
            <p>
              To respond to your inquiry, contact you, or follow up on your
              request
            </p>
            <p>To schedule property viewings and book appointments</p>
            <p>To improve our services and communications</p>
          </div>
          <div>
            <strong>Which form(s)</strong>
            <p>Contact & Sale Request forms</p>
            <p>Booking form</p>
            <p>All forms (in aggregated / anonymised form)</p>
          </div>
          <div>
            <strong>Legal Basis</strong>
            <p>
              Your consent (you provided the information knowing how it will be
              used)
            </p>
            <p>Your consent / performance of a service at your request</p>
            <p>
              Legitimate interest of the company, with respect for your privacy
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export function DataManagement({ date }) {
  return (
    <section className="max-w-6xl p-6 md:p-12 mx-auto text-lg text-gray-700 space-y-6">
      <h2 className="text-2xl md:text-3xl font-light text-blue-900  mb-4">
        {" "}
        Data Management
      </h2>{" "}
      <div>
        <strong>1. Consent</strong>
        <p>
          By submitting any of our forms, you voluntarily consent to our
          collecting and using your name, phone number, and email for the
          purposes described above. You may withdraw your consent at any time,
          by contacting us at info@letirealty.com. Once you withdraw consent, we
          will stop using your personal data for future purposes and delete it
        </p>
      </div>
      <div>
        <strong>2. Data Minimization</strong>
        <p>
          We only collect the data necessary to accomplish the stated purpose.
          We do not collect more data than is needed. For example, we ask for
          name, phone, and email because that is sufficient to contact you or
          schedule viewings. We avoid collecting unnecessary information.
        </p>
      </div>
      <div>
        <strong>3. Data Security</strong>
        <p>
          We keep your personal data safe. Some of the measures we take include:
        </p>
        <ul role="list" className="list-disc marker:text-sky-400">
          <li>
            Secure storage (password-protected systems, restricted access)
          </li>
          <li>Data access only by authorized personnel</li>
          <li>Use of encryption where appropriate</li>
          <li>Regular review of our security measures</li>
        </ul>
      </div>
      <div>
        <strong>4. Data Retention</strong>
        <p>
          We will retain your personal data only for as long as necessary for
          the purposes for which it was collected or as required by law. After
          that, we will securely delete or anonymize your data. If you have
          asked us to withdraw consent, we will delete your data within 90 days
          of your request.
        </p>
      </div>
      <div>
        <strong>5. Sharing Data / Third Parties</strong>
        <p>
          We do not share your personal data with third parties except when:
        </p>
        <ul role="list" className="list-disc marker:text-sky-400">
          <li>
            It is necessary to fulfill your request (e.g., to schedule a
            viewing)
          </li>
          <li>We are required by law / legal obligation</li>
          <li>With your explicit consent</li>
        </ul>
        <p>
          Any third party with whom data is shared must have appropriate
          security measures in place.
        </p>
      </div>
      <div>
        <strong>6. International Data Transfers</strong>
        <p>
          If in any case your data is transferred outside Kenya (e.g. to a
          service provider in another country), we will ensure that the country
          has comparable data protection laws or that appropriate safeguards are
          in place (contracts, standard clauses, etc.). We will inform you if
          this becomes necessary.
        </p>
      </div>
      <div>
        <strong>7. Rights of Data Subjects</strong>
        <p>
          You have a number of rights under the Data Protection Act, including:
        </p>
        <ul role="list" className="list-disc marker:text-sky-400">
          <li>
            <strong>Right to access</strong> the personal data we hold about you
          </li>
          <li>
            <strong>Right to correct</strong> any inaccurate or incomplete data
          </li>
          <li>
            <strong>Right to delete</strong> your personal data (erasure),
            subject to any legal obligations
          </li>
          <li>
            <strong>Right to object</strong> to processing of your data for
            certain purposes
          </li>
          <li>
            <strong>Right to withdraw consent</strong> at any time, for future
            processing
          </li>
          <li>
            <strong>Right to lodge a complaint</strong> with the Office of the
            Data Protection Commissioner if you believe your personal data has
            been mishandled
          </li>
        </ul>
      </div>
      <div>
        <strong>8. Contact and Complaints</strong>
        <p>
          If you have any questions about this policy, your data, or wish to
          make a complaint, you can contact our Data Protection Officer at:
        </p>
        <ul role="list" className="list-disc marker:text-sky-400">
          <li>Name: James O.</li>
          <li>Email: consultintuitive@gmail.com</li>
        </ul>
        <p>
          If you are not satisfied with our handling of your complaint, you have
          the right to escalate the matter to the Office of the Data Protection
          Commissioner in Kenya.
        </p>
      </div>
      <div>
        <strong>9. Updates to This Policy</strong>
        <p>
          We may update this Privacy Policy from time to time (for example, when
          legal rules change or we change our processes). When we make
          significant changes, we’ll notify you by posting the new policy on our
          website and/or via email. Please check this policy periodically for
          changes. The effective date of this policy is. <strong>{date}</strong>
        </p>
      </div>
    </section>
  );
}
