import image1 from "@/public/img1.jpg";
import image2 from "@/public/img2.jpg";
import image3 from "@/public/img3.jpg";
import image4 from "@/public/img4.jpg";
import image5 from "@/public/img5.jpg";
import image6 from "@/public/img6.jpg";
import image7 from "@/public/img7.jpg";
import image8 from "@/public/img8.jpg";
import image9 from "@/public/img9.jpg";
import image10 from "@/public/img10.jpg";
import image11 from "@/public/img11.jpg";
import image12 from "@/public/img12.jpg";

const properties = [
  {
    id: 1,
    image: image1,
    price: "$950,000",
    title: "Elegant Coastal Villa",
    location: "123 Luxury Lane, Beverly Hills",
    description:
      "An elegant coastal villa with panoramic ocean views, featuring a spacious terrace and luxurious interiors.",
    beds: 4,
    baths: 3,
    sqft: 2800,
    images: [
      {
        id: 1,
        url: image3,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image4,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image5,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image6,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR RENT",
    type: "House",
    status: ["New", "Featured", "Verified"],
    createdAt: "2025-06-19T01:38:35.135075",
    parkingspace: 2,
    petsallowed: true,
    verified: true,
    isnew: true,
    publisheddate: "2025-06-19",
    adnumber: "AD001",
    views: 1250,
    hasvideo: true,
    amenities: ["Ocean View", "Terrace", "Luxury Finishes", "Pool", "Gym"],
    notincluded: ["Utilities", "Internet", "Cleaning Service"],
  },
  {
    id: 2,
    image: image2,
    price: "$1,450,000",
    title: "Beachfront Paradise",
    location: "456 Beach Drive, Malibu",
    description:
      "A stunning beachfront property with direct access to the sand, perfect for sunbathing and water sports.",
    beds: 5,
    baths: 4,
    sqft: 3500,
    images: [
      {
        id: 1,
        url: image5,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image1,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image9,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image7,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR RENT",
    type: "Apartment",
    status: ["Featured"],
    createdAt: "2025-07-01T15:47:35.135099",
    parkingspace: 3,
    petsallowed: false,
    verified: false,
    isnew: false,
    publisheddate: "2025-07-01",
    adnumber: "AD002",
    views: 2840,
    hasvideo: true,
    amenities: [
      "Beach Access",
      "Water Sports Equipment",
      "Balcony",
      "Security",
    ],
    notincluded: ["Utilities", "Parking Fee", "Beach Equipment"],
  },
  {
    id: 3,
    image: image3,
    price: "$850,000",
    title: "Modern Urban Loft",
    location: "789 City Center, Downtown",
    description:
      "A modern loft in the heart of the city, featuring high ceilings and an open floor plan with stylish finishes.",
    beds: 3,
    baths: 2,
    sqft: 2000,
    images: [
      {
        id: 1,
        url: image3,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image6,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image5,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image1,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR SALE",
    type: "House",
    status: ["Featured"],
    createdAt: "2025-06-16T12:15:35.135107",
    parkingspace: 1,
    petsallowed: true,
    verified: false,
    isnew: false,
    publisheddate: "2025-06-16",
    adnumber: "AD003",
    views: 980,
    hasvideo: false,
    amenities: [
      "High Ceilings",
      "Open Floor Plan",
      "City View",
      "Modern Finishes",
    ],
    notincluded: ["Furniture", "Appliances", "HOA Fees"],
  },
  {
    id: 4,
    image: image4,
    price: "$1,100,000",
    title: "Charming Mountain Retreat",
    location: "321 Highland Road, Hollywood Hills",
    description:
      "A charming retreat nestled in the mountains, offering breathtaking views and a cozy fireplace for winter nights.",
    beds: 4,
    baths: 3.5,
    sqft: 3200,
    images: [
      {
        id: 1,
        url: image2,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image4,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image5,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image12,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR SALE",
    type: "New building",
    status: ["Featured", "Verified"],
    createdAt: "2025-06-18T13:41:35.135118",
    parkingspace: 2,
    petsallowed: true,
    verified: true,
    isnew: false,
    publisheddate: "2025-06-18",
    adnumber: "AD004",
    views: 1670,
    hasvideo: true,
    amenities: ["Mountain View", "Fireplace", "Deck", "Hiking Trails Access"],
    notincluded: ["Utilities", "Maintenance", "Property Tax"],
  },
  {
    id: 5,
    image: image5,
    price: "$1,800,000",
    title: "Smart Luxury Home",
    location: "567 Tech Avenue, Silicon Valley",
    description:
      "A state-of-the-art smart home with cutting-edge technology and eco-friendly features, designed for modern living.",
    beds: 6,
    baths: 5,
    sqft: 4500,
    images: [
      {
        id: 1,
        url: image8,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image4,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image5,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image10,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR SALE",
    type: "House",
    status: ["New", "Featured"],
    createdAt: "2025-06-19T21:54:35.135123",
    parkingspace: 4,
    petsallowed: true,
    verified: false,
    isnew: true,
    publisheddate: "2025-06-19",
    adnumber: "AD005",
    views: 3200,
    hasvideo: true,
    amenities: [
      "Smart Home Technology",
      "Solar Panels",
      "Electric Car Charging",
      "Home Theater",
      "Wine Cellar",
    ],
    notincluded: ["Furniture", "Smart Home Subscription", "Utilities"],
  },
  {
    id: 6,
    image: image6,
    price: "$700,000",
    title: "Family-Friendly Haven",
    location: "890 Suburban Lane, Santa Monica",
    description:
      "A family-friendly haven with a large backyard, perfect for kids and pets, located in a quiet neighborhood.",
    beds: 3,
    baths: 2,
    sqft: 2550,
    images: [
      {
        id: 1,
        url: image10,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image4,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image5,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image8,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR RENT",
    type: "Apartment",
    status: ["Featured", "Verified"],
    createdAt: "2025-06-07T09:07:35.135128",
    parkingspace: 2,
    petsallowed: true,
    verified: true,
    isnew: false,
    publisheddate: "2025-06-07",
    adnumber: "AD006",
    views: 1890,
    hasvideo: false,
    amenities: [
      "Large Backyard",
      "Playground",
      "Safe Neighborhood",
      "Pet-Friendly",
    ],
    notincluded: ["Utilities", "Lawn Maintenance", "Pet Deposit"],
  },
  {
    id: 7,
    image: image7,
    price: "$720,000",
    title: "Cozy Cottage Retreat",
    location: "890 Suburban Lane, Santa Monica",
    description:
      "A cozy cottage retreat with a charming garden, ideal for relaxing weekends and family gatherings.",
    beds: 3,
    baths: 2,
    sqft: 2500,
    images: [
      {
        id: 1,
        url: image5,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image7,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image12,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image1,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR RENT",
    type: "Apartment",
    status: ["Featured"],
    createdAt: "2025-06-11T03:16:35.135133",
    parkingspace: 1,
    petsallowed: false,
    verified: false,
    isnew: false,
    publisheddate: "2025-06-11",
    adnumber: "AD007",
    views: 1340,
    hasvideo: true,
    amenities: ["Garden", "Cottage Style", "Quiet Location", "Outdoor Seating"],
    notincluded: ["Utilities", "Garden Maintenance", "Furniture"],
  },
  {
    id: 8,
    image: image8,
    price: "$740,000",
    title: "Stylish Family Home",
    location: "890 Suburban Lane, Santa Monica",
    description:
      "A stylish family home with modern amenities and a spacious layout, perfect for entertaining guests.",
    beds: 3,
    baths: 2,
    sqft: 2400,
    images: [
      {
        id: 1,
        url: image3,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image4,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image5,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image9,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR SALE",
    type: "House",
    status: ["Featured", "Verified"],
    createdAt: "2025-06-22T00:35:35.135139",
    parkingspace: 2,
    petsallowed: true,
    verified: true,
    isnew: false,
    publisheddate: "2025-06-22",
    adnumber: "AD008",
    views: 2150,
    hasvideo: false,
    amenities: [
      "Modern Kitchen",
      "Spacious Layout",
      "Entertainment Area",
      "Updated Bathrooms",
    ],
    notincluded: ["Appliances", "Closing Costs", "HOA Fees"],
  },
  {
    id: 9,
    image: image9,
    price: "$760,000",
    title: "Chic Suburban Retreat",
    location: "890 Suburban Lane, Santa Monica",
    description:
      "A chic suburban retreat with a contemporary design, featuring a large deck for outdoor entertaining.",
    beds: 3,
    baths: 2,
    sqft: 2150,
    images: [
      {
        id: 1,
        url: image4,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image7,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image5,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image11,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR RENT",
    type: "New building",
    status: ["New", "Featured"],
    createdAt: "2025-06-06T16:31:35.135146",
    parkingspace: 2,
    petsallowed: false,
    verified: false,
    isnew: true,
    publisheddate: "2025-06-06",
    adnumber: "AD009",
    views: 1560,
    hasvideo: true,
    amenities: [
      "Large Deck",
      "Contemporary Design",
      "Outdoor Entertainment",
      "New Construction",
    ],
    notincluded: ["Utilities", "Deck Furniture", "Landscaping"],
  },
  {
    id: 10,
    image: image10,
    price: "$780,000",
    title: "Elegant Family Residence",
    location: "890 Suburban Lane, Santa Monica",
    description:
      "An elegant family residence with spacious living areas and a beautifully landscaped yard, perfect for family life.",
    beds: 3,
    baths: 2,
    sqft: 2850,
    images: [
      {
        id: 1,
        url: image2,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image4,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image5,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image12,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR RENT",
    type: "Apartment",
    status: ["New", "Featured"],
    createdAt: "2025-07-03T02:02:35.135151",
    parkingspace: 2,
    petsallowed: true,
    verified: false,
    isnew: true,
    publisheddate: "2025-07-03",
    adnumber: "AD010",
    views: 920,
    hasvideo: false,
    amenities: [
      "Landscaped Yard",
      "Spacious Living",
      "Family-Friendly",
      "Elegant Design",
    ],
    notincluded: ["Utilities", "Yard Maintenance", "Furniture"],
  },
  {
    id: 11,
    image: image11,
    price: "$800,000",
    title: "Charming Craftsman Home",
    location: "890 Suburban Lane, Santa Monica",
    description:
      "A charming craftsman home with original woodwork and a welcoming front porch, ideal for family gatherings.",
    beds: 3,
    baths: 2,
    sqft: 2200,
    images: [
      {
        id: 1,
        url: image1,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image4,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image5,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image7,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR SALE",
    type: "House",
    status: ["New", "Featured"],
    createdAt: "2025-06-19T04:11:35.135156",
    parkingspace: 1,
    petsallowed: true,
    verified: false,
    isnew: true,
    publisheddate: "2025-06-19",
    adnumber: "AD011",
    views: 1780,
    hasvideo: true,
    amenities: [
      "Original Woodwork",
      "Front Porch",
      "Craftsman Style",
      "Character Features",
    ],
    notincluded: ["Appliances", "Renovation Costs", "Property Tax"],
  },
  {
    id: 12,
    image: image12,
    price: "$820,000",
    title: "Spacious Family Retreat",
    location: "890 Suburban Lane, Santa Monica",
    description:
      "A spacious family retreat with ample room for everyone, featuring a large backyard and a cozy atmosphere.",
    beds: 3,
    baths: 2,
    sqft: 2600,
    images: [
      {
        id: 1,
        url: image5,
        alt: "Main living area",
        isMain: true,
      },
      {
        id: 2,
        url: image4,
        alt: "Kitchen view",
        isMain: false,
      },
      {
        id: 3,
        url: image5,
        alt: "Bedroom",
        isMain: false,
      },
      {
        id: 4,
        url: image8,
        alt: "Bathroom",
        isMain: false,
      },
    ],
    category: "FOR RENT",
    type: "Apartment",
    status: ["Featured"],
    createdAt: "2025-06-22T11:20:35.135161",
    parkingspace: 2,
    petsallowed: true,
    verified: false,
    isnew: false,
    publisheddate: "2025-06-22",
    adnumber: "AD012",
    views: 2340,
    hasvideo: false,
    amenities: [
      "Large Backyard",
      "Spacious Rooms",
      "Family-Friendly",
      "Cozy Atmosphere",
    ],
    notincluded: ["Utilities", "Backyard Maintenance", "Pet Fee"],
  },
];
export default properties;
