import {
  Heart,
  Share2,
  Play,
  Wifi,
  Car,
  Wind,
  Tv,
  Shield,
  Thermometer,
  MapPin,
  Bed,
  Bath,
  Dumbbell,
  WavesLadder,
  UsersRound,
  Shapes,
  Leaf,
  HousePlus,
  Fence,
  PawPrint,
  ThermometerSun,
  Cctv,
  Zap,
  Droplets,
  HousePlug,
  Globe,
  HouseWifi,
  Square,
  ArrowUp,
  WashingMachine,
  X,
  ChevronLeft,
  ChevronRight,
  CigaretteOff,
  Utensils,
  Shirt,
} from "lucide-react";

// Constants
const AMENITY_ICONS = {
  wifi: Wifi,
  heating: Thermometer,
  dishwasher: Utensils,
  parking: Car,
  ac: Wind,
  iron: Shirt,
  tv: Tv,
  laundry: WashingMachine,
  security: Cctv,
  "no-smoking": CigaretteOff,
  "24/7 security": Cctv,
  "electric fence": Zap,
  "water supply": Droplets,
  "backup generator": HousePlug,
  "internet ready": HouseWifi,
  "dstv/tv connections": Tv,
  balcony: Square,
  elevator: ArrowUp,
  "swimming pool": WavesLadder,
  "gym/fitness center": Dumbbell,
  clubhouse: UsersRound,
  "children's play area": Shapes,
  garden: Leaf,
  "laundry area": WashingMachine,
  "servant's quarters (dsq)": HousePlus,
  "gated community": Fence,
  "pet friendly": PawPrint,
  "solar water heating": ThermometerSun,
};

export default function AmenityIcon({
  iconName,
  className = "w-5 h-5 text-gray-600",
}) {
  const IconComponent = AMENITY_ICONS[iconName] || Shield;
  return <IconComponent className={className} />;
}
